name: storage_utility_example
description: Demonstrates how to use the storage_utility plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  storage_utility_windows:
    # When depending on this package from a real application you should use:
    #   storage_utility_windows: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  storage_utility_platform_interface: ^1.0.0
  intl: ^0.19.0
  path_provider: ^2.1.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
