name: storage_utility_platform_interface
description: A common platform interface for the storage_utility plugin.
version: 1.0.0
homepage: https://github.com/DeepHow/App-StorageUtility/tree/main/storage_utility_platform_interface

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - disk
  - storage
