name: storage_utility_windows
description: Windows implementation of the storage_utility plugin.
version: 1.0.0
homepage: https://github.com/DeepHow/App-StorageUtility/tree/main/storage_utility_windows

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: storage_utility
    platforms:
      windows:
        dartPluginClass: StorageUtilityWindows

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  storage_utility_platform_interface: ^1.0.0
  win32: ">=2.1.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - disk
  - storage
